name: EntityLogger
version: '${project.version}'
main: dev.twme.entitylogger.EntityLogger
api-version: '1.21'
author: TWME
description: Logs entity spawn
commands:
  entitylogger:
    description: Main command for EntityLogger
    usage: /entitylogger
    permission: entitylogger.command
permissions:
  entitylogger.use:
    description: Allows access to /entitylogger and use the check tool
    default: op
  entitylogger.reload:
    description: Allows access to /entitylogger reload
    default: op